var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx",
   "x  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  x",
   "x                                                               x  c           x",
   "x                                                               x              x",
   "x                                                               x  g           x",
   "x                                                               xxxxxxx      xxx",
   "x                                                               yyyyyyy     xxxx",
   "x                                                                          xxxxx",
   "x                                                                         xxxxxx",
   "x                  c c      c         c c            c                  x xxxxxx",
   "x                                                      c               xx xxxxxx",
   "x                                xxxx                    c             xx xxxxxx",
   "x          xxxx    xxx    xxxx   yyyy        xxxx                    x xx xxxxxx",
   "x   @      yyyy    yyy    yyyy               yyyy                   xx xx xxxxxx",
   "xxxxxxxxxx                        xxxxxxxxxxxxxx     xxxxxxxxxxx xxxxx xx xxxxxx",
   "xxxxxxxxxx                        xxxxxxxxxxxxxx     xxxxxxxxxxx xxxxx xx xxxxxx",
   "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!xxxxxxxxxxx!xxxxx!xx!xxxxxx",
   "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!xxxxxxxxxxx!xxxxx!xx!xxxxxx",
   "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx",
   "x  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  x",
   "x                                                                                  x",
   "x                                                                                  x",
   "x                                          xxxyyxxyyxx                             x",
   "x                                          xxxyyxxyyxx                             x",
   "x                                           xxxxxxxxx                             xx",
   "x                                           xxxxxxxxx                        xx    x",
   "x                                           xxxxxxxxx                   c    xx    x",
   "x             c      c      c         c c   xxxxxxxxx            g           xx    x",
   "x                                           xxxxxxxxx           xxx          xxx   x",
   "x                                xxxx       xxxxxxxxx           yyy          xx    x",
   "x             x      x     x     yyyy       xxxxxxxxx                        xx    x",
   "x   @         y      y     y                xxxxxxxxx                        xx    x",
   "xxxxxxxxxx                        xxxxx                                      xx   xx",
   "yyyyyyyyyy                        xxxxx        cc                            xx    x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx   xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxx   x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx   xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xx    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                 xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "x  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yy  yyx",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "x                                                                                            x",
   "x                                                                                            x",
   "x                                          xxxyyxxyyxx                c c                    x",
   "x                                          xxxyyxxyyxx                                       x",
   "x                                           xxxxxxxxx                                        x",
   "x                                           xxxxxxxxx            c           xx      xx      x",
   "x                   c c                     xxxxxxxxx            g           xxy     yy      x",
   "x                                           xxxxxxxxx           xxx          xx             xx",
   "x              xxxx   x                     xxxxxxxxx           yyy          xx             yx",
   "x              yyyy   y                     xxxxxxxxx                        xxx             x",
   "x   @                                       xxxxxxxxx                        xxy     xx      x",
   "xxxxxx                         xxxxx       xxxxxxxxxx                        xx      yy     xx",
   "yyyyyy                         yyyxxxxx   xxxxxxxxxxx                        xx             yx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx   xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxx             x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx   xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxy     xx      x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      yy     xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           c          c          c        c              xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                           xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxx!!xxxxxxxxxx!!xxxxxxx!!xxxxxxxxxxxxxxxxxxxxx"],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
